/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hrca' at '10/9/16 8:01 PM' with Gradle 3.0
 *
 * @author hrca, @date 10/9/16 8:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
